### ISSUE TITLE
make the README file more readable

### ISSUE THREAD

**Issue by AWIXOR-zz** [ans1genie/SQLi-eChallenge-2018-CloudInfrastructure#2]
You can separate the languages you used to explain in the Readme by adding titles.

**Comment by ans1genie** [comment]
Thank you  @AWIXOR  for opening the issue, I will do it

**Comment by ans1genie** [comment]
@AWIXOR means you want a translated version of the description in the readme file?

**Comment by AWIXOR-zz** [comment]
@ans1genie  No, just for good look It's better to separate the  the languages you used in the Readme.
I've made a PR to understand what I meant :)

**Comment by ans1genie** [comment]
Thank you, I didn't pay attention to it 
Thanks @AWIXOR 
The PR will be merged
